language: java
addons:
  sonarcloud:
    organization: "alejandro0334-github"
    token:
      secure: RSPMvIpM50sk3e05EISANvHNOUo9EUOrwD0Z33aiR0F4XZk+xp5vIgoGAUqcJWTcvSN3pdRyiVA02G/oAtOEkxo27q8k3fiQk2nsDtGGQy1KKxWRFEJDMrokJWsCjUhirxGB3UB5rYclS7jxRxpVJJMCuxFswQqKfdJG7iwZNNE6IF7LMt5Vn9mkTP7fgz8tMFvr4IcXm8g/LakpWpKUuTG38T4uiJLPIc9uWIz12sropnjW2CIcbC/I/SCWJcHUQRZ8DzkLjY1ft0DflAKEwkjyq6zQUB+h1T7K6IrHtXO+x4zUVHiTy3rnpKFij0PvHLT1hg4gmcv0z9/bfL5Rct9eHkD/gXBFgQLYmMnMtgbCNFnR08iIMe7yy4TqcWC9WPwHKA0pTsKLb4dku7pONU3jd91saALyFpz1dU9bFGu7uuBA6CHRYh33ozpFiI/0Bd2I6Zg2ZIObYxqLNL+k/Q7ItvEyMdUIt55UPhbe2RT9ywPgSwfarS3cJ12jWuRDT6011TXC10tYIPhzfOH/oJKGv9dCFC2CJ0tRng+1tRJo8xJZxzESuJ9t++m8VUyW5ufLOUoITpSWhw7pMG1EyHwbNy8minFXy+LuK1zy3HRElOoirvmm2weJQYQeIaqYCa+tY1WEugsGn1GdyEHkZjtv4QeHmcvQvrWKPrItghc=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar