language: java
addons:
  sonarcloud:
    organization: "alejandro0334-github"
    token:
      secure: Sju9gJlUCr4+edM+lPcQW6JQuMjaacj8DNjxyi7g6Azh418FTfaa0dWb7EHfH7leXcwjf+vZUe75jzDhncHm1YyEPJOPmRq4OOnmcat72rfsThRgdJzqmyh/X3Pe+t1UURcF/O7xy40nqsccat6z1NgpG1+HHYTV0HrwIOU6gKxbQ7q9nNRnn/9dvp9T6eQQM993NT2nw8fGTM857StidFEsjfgI0WOF7bzq1pXNwisfmcH8mOOm3aFuSUHUip+xSjaTtiSYLJJ0sPrfnwtC16UZfJQHP6TS681tx/P91bxTVPDO+Y0nNzT9L3aQ9GnWaWu7U7ruMJz4op/23+NJAetlCZj8D2sGFo3njzjX4oePDYHeDkTtYdJfsm1GwvimzFYPjRcp3aAvU2NOmG7/R/NqV8mwY9WalMg7J5QP+vbIqcBh2kBCd1jpu+IcCMApZt+Np0hyKarT8i9VYYUfhnjdnFgnsXu56A192vGeHr5cm6+FSbg7sDGF8tFrJkxkbhGObGZlgNhje9TpvOZ/kzQ1rQX1s8O9Nr9OUCisoggAlJtJRhF/YjoZKdS0M6X9qE97I4Pg7cWLNiYOZKlWMdqgGSHKLQkr8DToXaDpJN9ho9wcuQzfyezMsrpss9fdd9eriWnzivihh9YfQMjzG1iQdVpX3PyF+yI6zqhB3xE=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar